### ISSUE TITLE
사용자 폰트 다운로드 기능

### ISSUE THREAD

**Issue by HyopangWorld** [FontChecker/FontChecker-iOS#13]
폰트 다운로드 파일 url 입력시 폰트파일을 저장하고 추가할 수 있는 기능을 추가한다.

**Comment by CaptainWonJong** [comment]
@HyopangWorld 
어제 개발하신 프로그램을 테스트 해 봤는데, 기본 제공하는 폰트도 제 기준에선 굉장히 많은 것 같았습니다.
폰트를 추가로 다운로드 하지 않아도 될 것 같다고 생각하는데 의견 부탁드릴게요.

추가로 폰트선택할 때 선택하는 화면이 작았었는데 한 눈에 약 5~10개의 폰트종류가 보일 수 있도록 크기 더 크게 부탁드려도 될까요?

그 외에는 모두 좋았습니다. :)

**Comment by HyopangWorld** [comment]
우선 답변 감사드립니다. 👍
기본 제공 폰트가 많긴 하지만, 아마 디자이너가 기본 제공 외의 폰트를 사용하는 경우가 많을 것 같습니다.
따라서 기본 제공 폰트를 넣고, 따로 다운로드하여 추가하는 기능이 있다면 좋을 것 같습니다.
챌린지가 끝나는대로 이 부분은 @wishJinit 와 협의 해보겠습니다 :)
